version: '3.9'

services:
  crud_go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_go
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:${PORT}/" ]
      timeout: 3s
      retries: 3