// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name  string `json:"name"`
	Phone string `json:"phone"`
	Email string `json:"email"`
}

type DeleteUserResponse struct {
	DeletedUserID string `json:"deletedUserId"`
}

type SoftdeleteUserInput struct {
	Deleted bool `json:"deleted"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
	Email *string `json:"email,omitempty"`
}
